---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_connection: ssh

project:
  hosts:
    develop:
      ansible_host: 178.49.148.61
      ansible_port: 822
      ansible_user: ubuntu

    stage:
      ansible_host: 20.74.86.112
      ansible_port: 22
      ansible_user: ubuntu